stages:
- build
- containerize

cache:
  paths: 
  - ./generator-runner/target/

build:
  stage: build
  image: maven:3-jdk-8
  script:
  - mvn package
  artifacts:
    untracked: true
    paths:
      - "./generator-runner/target/"
    expire_in: 1 week

containerize:
  stage: containerize
  image: docker:latest
  services:
  - docker:dind
  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --build-arg JAR_FILE --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
