server:
  host: localhost
  port: 8081
  contextPath: /generatorgateway
  serviceUrl: http://localhost:8081/generatorgateway
  config:
    generatorUser:
    generatorPassword:

vorto:
  serverUrl: http://localhost:8080/infomodelrepository
  tenantId: default
